// flow-typed signature: 40092b9ddab797a02cfd6052ad94cad1
// flow-typed version: <<STUB>>/accounting_v^0.4.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'accounting'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'accounting' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'accounting/accounting' {
  declare module.exports: any;
}

declare module 'accounting/accounting.min' {
  declare module.exports: any;
}

declare module 'accounting/demo-resources/js/libs/jquery.min' {
  declare module.exports: any;
}

declare module 'accounting/demo-resources/js/prettify' {
  declare module.exports: any;
}

declare module 'accounting/tests/jasmine/core/formatMoneySpec' {
  declare module.exports: any;
}

declare module 'accounting/tests/jasmine/core/formatNumberSpec' {
  declare module.exports: any;
}

declare module 'accounting/tests/jasmine/core/unformatSpec' {
  declare module.exports: any;
}

declare module 'accounting/tests/jasmine/lib/jasmine/jasmine-html' {
  declare module.exports: any;
}

declare module 'accounting/tests/jasmine/lib/jasmine/jasmine' {
  declare module.exports: any;
}

declare module 'accounting/tests/qunit/methods' {
  declare module.exports: any;
}

declare module 'accounting/tests/qunit/speed' {
  declare module.exports: any;
}

declare module 'accounting/tests/qunit/vendor/jquery' {
  declare module.exports: any;
}

declare module 'accounting/tests/qunit/vendor/jslitmus' {
  declare module.exports: any;
}

declare module 'accounting/tests/qunit/vendor/qunit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'accounting/accounting.js' {
  declare module.exports: $Exports<'accounting/accounting'>;
}
declare module 'accounting/accounting.min.js' {
  declare module.exports: $Exports<'accounting/accounting.min'>;
}
declare module 'accounting/demo-resources/js/libs/jquery.min.js' {
  declare module.exports: $Exports<'accounting/demo-resources/js/libs/jquery.min'>;
}
declare module 'accounting/demo-resources/js/prettify.js' {
  declare module.exports: $Exports<'accounting/demo-resources/js/prettify'>;
}
declare module 'accounting/tests/jasmine/core/formatMoneySpec.js' {
  declare module.exports: $Exports<'accounting/tests/jasmine/core/formatMoneySpec'>;
}
declare module 'accounting/tests/jasmine/core/formatNumberSpec.js' {
  declare module.exports: $Exports<'accounting/tests/jasmine/core/formatNumberSpec'>;
}
declare module 'accounting/tests/jasmine/core/unformatSpec.js' {
  declare module.exports: $Exports<'accounting/tests/jasmine/core/unformatSpec'>;
}
declare module 'accounting/tests/jasmine/lib/jasmine/jasmine-html.js' {
  declare module.exports: $Exports<'accounting/tests/jasmine/lib/jasmine/jasmine-html'>;
}
declare module 'accounting/tests/jasmine/lib/jasmine/jasmine.js' {
  declare module.exports: $Exports<'accounting/tests/jasmine/lib/jasmine/jasmine'>;
}
declare module 'accounting/tests/qunit/methods.js' {
  declare module.exports: $Exports<'accounting/tests/qunit/methods'>;
}
declare module 'accounting/tests/qunit/speed.js' {
  declare module.exports: $Exports<'accounting/tests/qunit/speed'>;
}
declare module 'accounting/tests/qunit/vendor/jquery.js' {
  declare module.exports: $Exports<'accounting/tests/qunit/vendor/jquery'>;
}
declare module 'accounting/tests/qunit/vendor/jslitmus.js' {
  declare module.exports: $Exports<'accounting/tests/qunit/vendor/jslitmus'>;
}
declare module 'accounting/tests/qunit/vendor/qunit.js' {
  declare module.exports: $Exports<'accounting/tests/qunit/vendor/qunit'>;
}
