// flow-typed signature: f93b5fb64b2f26b8bc731e02dc847a00
// flow-typed version: <<STUB>>/watchtower-autocomplete-values-fetcher_v^1.0.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'watchtower-autocomplete-values-fetcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'watchtower-autocomplete-values-fetcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'watchtower-autocomplete-values-fetcher/dist/index' {
  declare module.exports: any;
}

declare module 'watchtower-autocomplete-values-fetcher/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'watchtower-autocomplete-values-fetcher/dist/index.js' {
  declare module.exports: $Exports<'watchtower-autocomplete-values-fetcher/dist/index'>;
}
declare module 'watchtower-autocomplete-values-fetcher/src/index.js' {
  declare module.exports: $Exports<'watchtower-autocomplete-values-fetcher/src/index'>;
}
